## Datasource
spring:
  config:    import: openapi.yml
        datasource:    url: jdbc:postgresql://localhost:5432/gira
    username: postgres
    password: admin
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      
  jackson:
    serialization:
      fail-on-empty-beans: false
      
  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver
    
springdoc:  swagger-ui:    path: /swagger-ui.html
  api-docs:    path: /openapi/v3/api-docs
  packages-to-scan:    - Cybersoft.javabackend.girajava14taithan
    